version: "3.8"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ../webapp:/webapp

    depends_on:
      db:
        condition: service_healthy  # Ensure DB is ready before app starts

  db:
    image: postgres:13-alpine  # Lightweight PostgreSQL image
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tanzeem
    healthcheck:  # Ensures DB is ready before app starts
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persistent storage


volumes:
  pg_data:
